### ISSUE TITLE
[Feature request] Use bitbucket roles in package-access configuration

### ISSUE THREAD

**Issue by ath88** [idangozlan/verdaccio-bitbucket#6]
I considered whether functionality like the following might be interesting:
```
auth:
  bitbucket:
    allow: TeamA(admin|member)
...
packages:
  '@myscope/*':
    allow_access: TeamA(admin), TeamA(member)
    allow_publish: TeamA(admin)
```
This will require this plugin to return a bit more information about the authenticated user, but might open up some nice options.

I already discussed this feature with @juanpicado on gitter, one of the main authors of verdaccio. He might be able to chime in.
